### ISSUE TITLE
feature: 添加搜索和时间线功能

### ISSUE THREAD

**Issue by chuwt** [yuzhouu/swallow#1]
小伙子急需添加`搜索`和`时间线`这两个功能

**Comment by yuzhouu** [comment]
- will add archive soon, 
- search config is to complicate for most user. User must sign up algolia and pass the SECRET API KEY through github workflow env. So search won't add to project

**Comment by yuzhouu** [comment]
- will add archive soon
- search config is to complicate for most user. User must sign up algolia and pass the SECRET API KEY through github workflow env. So search won't add to project
